# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: BootCamp Next js

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm ci

    - name: Echo on push
      run: |
        echo "Push event detected!"
